
server:
  port: 8082
  
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource: 
    url: jdbc:mysql://localhost:3306/provider?useTimezone=true&serverTimezone=UTC
    username: root
    password: root